kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-data
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
    
